---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 30347.
--- DateTime: 2025/4/17 15:28
---
--订单id
local voucherId = ARGV[1]
--用户id
local userId = ARGV[2]
--数据key
local stockKey = "seckill:stock:" .. voucherId
local orderKey = "seckill:order:" .. voucherId
--判断库存是否充足
if (tonumber(redis.call('get',stockKey))<=0) then
    --库存不足
    return 1
end
--判断用户是否下单
if (redis.call('sismember',orderKey,userId)==1) then
    --用户已经下过单
    return 2
end
--扣减库存
redis.call('incrby',stockKey,-1)
--将userId传入当前优惠券的set集合
redis.call('sadd',orderKey,userId)
return 0
